Algoritmo "Cuaberto"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/03/2022
Var
// Seção de Declarações das variáveis 

Soma,num1,num2:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, ...

escreva("Ola boa pessoa. Digite um numero Bacana ai: ")
leia(num1)
escreva("Bão. Agora Digite outro numero: ")
leia(num2)
soma :=num1+num2
escreva("Tó o resultado", soma)


Fimalgoritmo